# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20180110_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='food',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='search',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
