# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20180110_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='location',
            field=models.CharField(max_length=40),
        ),
    ]
